app:
  rest:
    factory:
      is-produce:
        url: https://localhost:8081/factory/api/is-can-produce
        timeout: 5000
      assemble:
        url: https://localhost:8081/factory/api/assemble
        timeout: 5000
  kafka:
    bootstrap-servers: localhost:29092
    topics:
      is-ready: factory.is.ready
    truststore:
      location: /home/pongpat/Documents/Fluke-Machine/downloads/ktb/DGL/poc/gen-key/client.truststore.jks
      password: clientsecret
    security:
      username: magickiat
      password: client-secret
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/showroom
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
