apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
data:
  spring.datasource.username: {{ .Values.secrets.spring.datasource.username | b64enc | quote }}
  spring.datasource.password: {{ .Values.secrets.spring.datasource.password | b64enc | quote }}
  spring.datasource.url: {{ .Values.secrets.spring.datasource.url | b64enc | quote }}