{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}-service-account
  labels:
{{ include "helm.labels" . | nindent 4 }}
{{- end -}}
