apiVersion: v1
kind: Service
metadata:
  name: showroom-service
  namespace: car-factory-dev
  labels:
    app: showroom-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: showroom-deployment
