app:
  rest:
    factory:
      is-produce:
        url: https://factory:8080/factory/api/is-can-produce
        timeout: 5000
      assemble:
        url: https://factory:8080/factory/api/assemble
        timeout: 5000
  kafka:
    bootstrap-servers: kafka:9092
    topics:
      is-ready: factory.is.ready
    truststore:
      location: /home/app/client.truststore.jks
      password: clientsecret
    security:
      username: magickiat
      password: client-secret
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://mysql:3306/showroom
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
